[tools]
node = "22"

# Linters
"aqua:rhysd/actionlint" = "1.7.7"
"npm:@commitlint/cli" = "19.8.1"
"npm:eslint" = "8.57.1"
"npm:prettier" = "3.5.3"

# Build
"npm:@vercel/ncc" = "0.36.1"

# Others
"npm:renovate" = "40.11.7"

[tasks.build]
run = "ncc build index.js -o dist"

[tasks.lint]
run = "eslint . --fix"

[tasks."lint:check"]
run = "eslint ."

[tasks.format]
run = "prettier --write ."

[tasks."format:check"]
run = "prettier --check ."