[tools]
node = "22"
gh = "2"

# =================================================================================================
# CI Tools
# =================================================================================================
"npm:renovate" = "40"
"aqua:rhysd/actionlint" = "1"
"npm:@commitlint/cli" = "19"
