---
name: Folder Matrix
description: Generates a matrix of subdirectories for parallelizing GitHub Actions jobs
author: Mircea-Pavel Anton

inputs:
  path:
    description: Path to the directory to scan for subdirectories
    required: true
    default: '.'
  include-hidden:
    description: Whether to include hidden directories (starting with .)
    required: false
    default: 'false'
  exclude:
    description: Comma-separated list of directory names to exclude
    required: false
    default: ''
  filter:
    description: Regular expression pattern to filter directory names (only matching directories will be included)
    required: false
    default: ''
  metadata-file:
    description: Path to metadata file within each subdirectory (e.g., metadata.json, Chart.yaml)
    required: false
    default: ''
  changed-only:
    description: Whether to include only directories with changes
    required: false
    default: 'false'
  github-token:
    description: GitHub token used to get changed files (required when changed-only is true)
    required: false

outputs:
  matrix:
    description: JSON array of subdirectory names for use in matrix strategy

runs:
  using: node24
  main: dist/index.js
