---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: ESLint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push:
    paths:
      - '**.js'
      - '.eslint.config.mjs'
      - '.eslintignore'
      - 'package*.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup mise
        uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint:check
