---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push:
    paths:
      - '**.js'
      - 'package*.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup mise
        uses: jdx/mise-action@429184fe4bc03ec959a8c13a993f514e6633ed3d # v2.3.0

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Upload coverage report
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
        with:
          file: ./coverage/lcov.info
